config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :users
  resources :questions
  resources :articles
  resources :messages
  resources :plan_requests
  resources :videos
  resources :plans
  
 

  get 'auth/:provider/callback' => 'sessions#social_auth'

  get 'make_payment' => 'plan_requests#make_payment'
  post 'send_payment' => 'plan_requests#send_payment' 

  get 'plans/new/:to_user/:request_id' => 'plans#new'
  get 'videos/show/:id' => 'videos#show'
  get 'videos/:id/delete' => 'videos#delete'
  get 'videos/:id/make_featured' => 'videos#make_featured'
  get 'videos/category/:category' => 'videos#index'

  get 'articles/:id/delete' => 'articles#delete'
  get 'questions/:id/delete' => 'questions#delete'
  get 'comments/:id/delete' => 'comments#delete'
  post 'questions/upvote' => 'comments#upvote'
  post 'questions/downvote' => 'comments#downvote'
  
  post 'discussions/change_category' => 'questions#change_category'
  get 'discussions/change_category' => 'questions#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'receive_payment_123875136516898791374817348' => 'plan_requests#new'

  post 'add_comment' => 'comments#create'
end

app/models/question.rb
class Question < ActiveRecord::Base
    has_many :comments
    
    validates :title, presence: true, length: { minimum: 10, maximum: 70}
    validates :content, presence: true, length: {minimum: 100, maximum: 3000}
    validates :user_id, presence: true
    validates :category, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def new
        check_user
        @question = Question.new
    end

    def create
        check_user
        @question = Question.new(title: params[:question][:title], 
            content: params[:question][:content], category: params[:category], user_id: session[:current_user])
        if @question.save
            flash[:success] = "Question successfully added."
            redirect_to questions_url
        else
            flash[:danger] = "An error occured whilst trying to add your question please try again."
            render 'new'
        end
    end

    def index
        @questions = Question.order(:created_at => :desc).paginate(:page => params[:page], :per_page => 10)
    end

    def delete
        admin_check
        @question = Question.find(params[:id]).destroy
        redirect_to questions_url
    end

    def show
        @question = Question.find(params[:id])
        @comments = Comment.where(:question_id => params[:id]).order("points DESC, created_at DESC").paginate(:page => params[:page], :per_page => 5)
    end
    
    def change_category
        category = params[:category]
        if category == "all"
            @questions = Question.order(:created_at => :desc).paginate(:page => params[:page], :per_page => 10)
        else
            @questions = Question.where(:category => category).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
        end
        @current_category = category
        render 'index'
    end

    private
        def check_user
            if session[:current_user] == nil
                flash[:danger] = "Please log in, or create an account, in order to post a question."
                redirect_to root_url + '/login'
            end
        end

        def admin_check
            if User.find(session[:current_user]).is_admin == false
                redirect_to root_url
                flash[:danger] = "You do not have access to this part of the web app."
            end
        end
                
end

app/helpers/questions_helper.rb
module QuestionsHelper
    def count_comments_in_question(question)
        @comments = 0
        main_comments = Comment.where(:question_id => question.id)
        main_comments.each do |main_comment|
            count_comments_in_comment(main_comment)
        end
        return @comments
    end

    def count_comments_in_comment(comment)
        @comments += 1
        main_comments = Comment.where(:comment_id => comment.id)
        main_comments.each do |main_comment|
            count_comments_in_comment(main_comment)
        end
    end
end

app/views/questions/_question.html.erb
<div class="question row">
<a class="question-partial" href="<%= root_url + 'questions/' + question.id.to_s %>">
<div class="col-md-12 question-box">
<h3><%= question.title %></h3>
    <p>
    <!--<%= Comment.where(:question_id => question.id).count.to_s + ' comments' %></br> _-->
    <%= count_comments_in_question(question).to_s + ' comments' %></br>
    <%= distance_of_time_in_words(question.created_at, Time.now, include_seconds: true) + " ago" %></p>
<% if session[:current_user] != nil %>
        <% if User.find(session[:current_user]).is_admin %>
            <%= link_to '[delete]', root_url + 'questions/' + question.id.to_s + '/delete' %>
        <% end %>
    <% end %>
</div>
</a>
</div>


<script>
  $(document).ready(new function(){
    $('.question-box').hover(
      
      function() {
      $(this).css('background', 'black');
      $(this).children().css('color', 'white');
      $(this).children().children().css('color', 'white');
    }, 
    
      function(){
        $(this).css('background', 'white');
        $(this).children().css('color', 'black');
        $(this).children().children().css('color', 'black');
    });
  });
</script>

app/views/questions/index.html.erb
<div class="col-sm-12 col-md-6">
<h2> Have a question? Want to share something interesting? Then just go ahead and start a new thread </h2>
<%= button_to 'START A THREAD', new_question_url, :class => "btn btn-primary", :method => 'get' %></li>
</div>

<div class="col-sm-12 col-md-6">
<h2>Threads:</h2>

<h4>Category:</h4>
<form action='<%= root_url %>discussions/change_category' method='post' %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <select id="category_select" name="category">
        <option value="all"> All </option>
        <option value="questions"> Simple Questions </option>
        <option value="motivation"> Motivation </option>
		<option value="cardio"> Cardio </option>
		<option value="workout"> Working out </option>
		<option value="general"> General/Other </option>
    </select>
</form>

<% if @questions.count == 0 %>
    <h4>There aren't any threads in this category, be the first to start one! </h4>
<% end %>

<% @questions.each do |question| %>
    <%= render question %>
<% end %>

<%= will_paginate @questions %>
</div>


<script>
$(document).ready(function (){
    var element = document.getElementById('category_select');
    var category = "<%= @current_category %>";
    
    if(category == ""){
        element.value = "all";
    } else {
        element.value = category;    
    }
    
    $("#category_select").change(function() {
       this.form.submit(); 
    });
});
</script>

app/views/questions/new.html.erb
<h2>Submit thread:</h2>

<%= form_for @question do |f| %>

    <% if @question.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@question.errors.count, 
			  "errors") %>
		    <ul>
			<% @question.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
        </div>
	</div>
    <% end %>

    <%= f.label :title %></br>
    <%= f.text_field :title, :class => 'col-md-12' %></br>
	
	<select name="category">
		<option value="questions"> Simple Questions </option>
		<option value="motivation"> Motivation </option>
		<option value="cardio"> Cardio </option>
		<option value="workout"> Working out </option>
		<option value="general"> General/Other </option>
	</select>

    <%= f.label :content %></br>
    <%= f.cktext_area :content, :class => 'col-md-12', :id => 'content-box' %></br>

    <%= f.submit 'Submit thread' %>
<% end %>

app/views/questions/show.html.erb
    <div class="question-text row">
    <div class="panel panel-default">
        <h2 class="panel-heading"><%= @question.title %></h2>
        <p class="panel-content question_content" id='content'>
            <%= @question.content.html_safe %>
        </p>
    </div>

    <% if @comments.count == 0 %>
        <h4>No one has commented yet, be the first to do so! </h4>
    <% end %>

    <% @comments.each do |comment| %>
            <%= render comment %>
        <% end %>
    <%= will_paginate @comments %>
    <% if session[:current_user] != nil %>
        </br><button id='add_comment'>Add comment</button>
    <% end %>
    <div id="new_comments">
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#add_comment').click(function() {
            $('#new_comments').append(
                "<form method=POST action='<%= root_url + 'add_comment' %>'>" +
                    "<input style='height: 9em; width: 32em;' type='text_area' name='content' placeholder='Add comment'></br>" +
                    "<input type='hidden' name='question_id' value='<%= @question.id %>'>" +
                    "<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>" +
                    "<input type='submit' value='Add comment'>" +
                "</form>"         
            );
            $('#add_comment').remove();}
        )
    });
</script>