config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :users
  resources :questions
  resources :articles
  resources :messages
  resources :plan_requests
  resources :videos
  resources :plans
  
 

  get 'auth/:provider/callback' => 'sessions#social_auth'

  get 'make_payment' => 'plan_requests#make_payment'
  post 'send_payment' => 'plan_requests#send_payment' 

  get 'plans/new/:to_user/:request_id' => 'plans#new'
  get 'videos/show/:id' => 'videos#show'
  get 'videos/:id/delete' => 'videos#delete'
  get 'videos/:id/make_featured' => 'videos#make_featured'
  get 'videos/category/:category' => 'videos#index'

  get 'articles/:id/delete' => 'articles#delete'
  get 'questions/:id/delete' => 'questions#delete'
  get 'comments/:id/delete' => 'comments#delete'
  post 'questions/upvote' => 'comments#upvote'
  post 'questions/downvote' => 'comments#downvote'
  
  post 'discussions/change_category' => 'questions#change_category'
  get 'discussions/change_category' => 'questions#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'receive_payment_123875136516898791374817348' => 'plan_requests#new'

  post 'add_comment' => 'comments#create'
end

app/models/plan_request.rb
class PlanRequest < ActiveRecord::Base
    validates :gender, presence: true
    validates :want_to, presence: true
    validates :unit, presence: true
    validates :user_id, presence: true

    validate :age_cannot_be_negative, :weight_validation, :height_validation

    def age_cannot_be_negative
        if age.present? && age <= 5
            errors.add(:age, "is invalid.")
        end
    end

    def weight_validation
        if weight.present? && (weight < 10 || weight > 400)
            errors.add(:weight, "is invalid.")
        end
    end

    def height_validation
        if height.present? && height <= 0
            errors.add(:height, "cannot be negative.")
        end
    end
end

app/controllers/plan_requests_controller.rb
class PlanRequestsController < ApplicationController

    def new
        log_in_check
        @user = User.find(session[:current_user])
        @user.payments += 1
        @user.save
        @plan_request = PlanRequest.new
    end

    def create
        log_in_check
        payment_check
        @plan_request = PlanRequest.new(plan_params)
        @plan_request.answered = false
        if @plan_request.save
            flash[:success] = "Successfully sent plan request."
            @user = User.find(session[:current_user])
            @user.payments -= 1
            @user.save
            redirect_to root_url
        else 
            flash[:danger] = "An error occured whilst trying to request plan, please check the information you sent and try again."
            render 'new'
        end
    end

    def index
        admin_check
        @plan_requests = PlanRequest.all().order(:created_at => :desc).paginate(:page => params[:page], :per_page => 5)
        @plan = Plan.new
    end

    def make_payment
        log_in_check
    end

    def send_payment
        log_in_check

        credit_card = ActiveMerchant::Billing::CreditCard.new(
            :first_name => params[:first_name],
            :last_name => params[:last_name],
            :number => params[:card_number],
            :month => params[:month],
            :year => params[:year],
            :verification_value => params[:verification_number]
        )

        if credit_card.valid?
            gateway = ActiveMerchant::Billing::PayflowGateway.new(
                :login => 'LOG_IN_ID',
                :password => 'PASSWORD'
            )
            response = gateway.purchase(1000, credit_card)
            if response.success?
                flash[:success] = "Payment was made, please wait for us to get back to you."
                @user = User.find(session[:current_user])
                @user.payments += 1
                @user.save
                redirect_to new_plan_request_path
            else
                flash[:danger] = "An error occured while trying to make the payment, you will not be charged. Please try again."
            end
        else
            flash[:danger] = "An error occured while trying to make the payment, you will not be charged. Please try again."
            credit_card.errors.each do |err|
                flash[:danger] += err.to_s
            end
        end
        redirect_to plans_url
    end

    private
        def plan_params
            params.require(:plan_request).permit(:gender, :age, :weight, :height, :comments, :want_to, :unit, :user_id)
        end

        def log_in_check
            if session[:current_user] == nil
                flash[:danger] = "Please log in to continue."
                redirect_to root_url + 'login'
            end
        end

        def admin_check
            if User.find(session[:current_user]).is_admin == false
                redirect_to root_url
                flash[:danger] = "You do not have access to this part of the web app."
            end
        end

        def payment_check
            if User.find(session[:current_user]).payments < 1
                flash[:danger] = "You need to make a payment, before accessing this page."
                redirect_to root_url + 'make_payment'
            end
        end
end

app/helpers/plan_requests_helper.rb
module PlanRequestsHelper
end

app/views/plan_requests/_plan_request.html.erb
<div class="col-12 request">
    Name: <%= User.find(plan_request.user_id).name %> </br>
    Age: <%= plan_request.age %> </br>
    Unit: <%= plan_request.unit %> </br>
    Weight: <%= plan_request.weight %> </br>
    Height: <%= plan_request.height %> </br>
    Gender: <%= plan_request.gender %> </br>
    Want to: <%= plan_request.want_to %> </br>
    Additional Comments: <%= plan_request.comments %> </br>

    <%= button_to 'Reply', new_plan_path + '/' + plan_request.user_id.to_s + '/' + plan_request.id.to_s, :method => 'get' %>
</div>

app/views/plan_requests/index.html.erb
<h2>Plan Requests:</h2>
<% @plan_requests.each do |plan_request| %>
    <%= render plan_request %>
<% end %>

<%= will_paginate @plan_requests %>

app/views/plan_requests/make_payment.html.erb
<h2>Make payment:</h2>
<!--
<form action="send_payment" method="POST">
    <label>First name</label></br>
    <input type="text_field" name="first_name"></br>
    <label>Last name</label></br>
    <input type="text_field" name="last_name"></br>

    <label>Card number</label></br>
    <input type="text_field" name="card_number"></br>

    <label>Expiration Date</label>(Months are from 1 to 12)</br>
    <input class="col-xs-1 col-sm-1 col-md-1" type="text_field" name="month" placeholder="MM">
    <input class="col-xs-4 col-sm-4 col-md-4" type="text_field" name="year" placeholder="YYYY"></br></br>

    <label>Verification code(CID, CVC2, CVV2)</label></br>
    <input type="text_field" name="verification_number">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <input class="btn-primary" type="submit" value="MAKE PAYMENT" >

</form>
-->

<h4> We use paypal, as it is a very popular option, it's easy to use and secure. You can use your credit/debit in paypal if you just link them to your account.</h4>
<div style="height: 15em; width: 15em;">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="EVGXE694DV5N6">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
</div>

app/views/plan_requests/new.html.erb
<h2>Request plan:</h2>

<%= form_for @plan_request do |f| %>

    <% if @plan_request.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@plan_request.errors.count, 
			  "errors") %>
		    <ul>
			<% @plan_request.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
        </div>
	</div>
    <% end %>

    <%= f.label :age %></br>
    <%= f.text_field :age %></br></br>

    <label for="unit of measurement"> What unit measurement system are you using: </label></br>
    <input type="radio" name="plan_request[unit]" value="metric">Metric (kg, cm)</br>
    <input type="radio" name="plan_request[unit]" value="imperial">Imperial (pounds, inches)</br></br>

    <%= f.label :weight %></br>
    <%= f.text_field :weight %></br></br>

    <%= f.label :height %></br>
    <%= f.text_field :height %></br></br>

    <label for="Gender"> Gender: </label></br>
    <input type="radio" name="plan_request[gender]" value="male"> Male<br>
    <input type="radio" name="plan_request[gender]" value="female"> Female<br></br>

    <label for="Want to">Want to:</label> </br>
    <input type="radio" name="plan_request[want_to]" value="cut"> Cut </br>
    <input type="radio" name="plan_request[want_to]" value="bulk"> Bulk up </br>
    <input type="radio" name="plan_request[want_to]" value="mantain"> Maintain </br></br>

    <input type="hidden" name="plan_request[user_id]" value="<%= session[:current_user] %>">

    <%= f.label :comments %></br>
    <%= f.text_area :comments %></br>

    <%= f.submit 'Submit' %>
<% end %>