config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :users
  resources :questions
  resources :articles
  resources :messages
  resources :plan_requests
  resources :videos
  resources :plans
  
 

  get 'auth/:provider/callback' => 'sessions#social_auth'

  get 'make_payment' => 'plan_requests#make_payment'
  post 'send_payment' => 'plan_requests#send_payment' 

  get 'plans/new/:to_user/:request_id' => 'plans#new'
  get 'videos/show/:id' => 'videos#show'
  get 'videos/:id/delete' => 'videos#delete'
  get 'videos/:id/make_featured' => 'videos#make_featured'
  get 'videos/category/:category' => 'videos#index'

  get 'articles/:id/delete' => 'articles#delete'
  get 'questions/:id/delete' => 'questions#delete'
  get 'comments/:id/delete' => 'comments#delete'
  post 'questions/upvote' => 'comments#upvote'
  post 'questions/downvote' => 'comments#downvote'
  
  post 'discussions/change_category' => 'questions#change_category'
  get 'discussions/change_category' => 'questions#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'receive_payment_123875136516898791374817348' => 'plan_requests#new'

  post 'add_comment' => 'comments#create'
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    has_many :comments
    
    validates :content, presence: true, length: { minimum: 4, maximum: 5000 }
end

app/models/comments_point.rb
class CommentsPoint < ActiveRecord::Base
    belongs_to :users
    belongs_to :comments
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    validates :to_user, presence: true
    validates :title, presence: true
    validates :content, presence: true, length: { minimum: 300 }
end

app/models/plan_request.rb
class PlanRequest < ActiveRecord::Base
    validates :gender, presence: true
    validates :want_to, presence: true
    validates :unit, presence: true
    validates :user_id, presence: true

    validate :age_cannot_be_negative, :weight_validation, :height_validation

    def age_cannot_be_negative
        if age.present? && age <= 5
            errors.add(:age, "is invalid.")
        end
    end

    def weight_validation
        if weight.present? && (weight < 10 || weight > 400)
            errors.add(:weight, "is invalid.")
        end
    end

    def height_validation
        if height.present? && height <= 0
            errors.add(:height, "cannot be negative.")
        end
    end
end

app/models/question.rb
class Question < ActiveRecord::Base
    has_many :comments
    
    validates :title, presence: true, length: { minimum: 10, maximum: 70}
    validates :content, presence: true, length: {minimum: 100, maximum: 3000}
    validates :user_id, presence: true
    validates :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    has_many :questions
    has_many :comments

    validates :name, presence: true, length: { minimum: 3, maximum: 40 }
    validates :email, presence: true, length: { minimum: 9, maximum: 40}
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
    def count_comments_in_question(question)
        @comments = 0
        main_comments = Comment.where(:question_id => question.id)
        main_comments.each do |main_comment|
            count_comments_in_comment(main_comment)
        end
        return @comments
    end

    def count_comments_in_comment(comment)
        @comments += 1
        main_comments = Comment.where(:comment_id => comment.id)
        main_comments.each do |main_comment|
            count_comments_in_comment(main_comment)
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlfaLife - Health and Fitness</title>
  <meta name="description" content="Affordable fitness plans and articles on topics such as propper eating, working out, keeping a diet, etc.">
  <meta name="keywords" content="fitness, health, diet, plan">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
  
  <div class="col-xs-0 col-md-1"></div>
  <div class="col-xs-12 col-sm-12 col-md-10 wrapper">
  
  <div class="banner-nav">

    <div class="navbar">
      <div class="row">
      <%= image_tag "banner-with-text", :class => "col-sm-12", :id => "banner" %>
      </div>
      <ul class="row navigation-bar">
        <li class="col-md-2 navbar-button"><%= link_to 'HOME', root_url, :class => 'navbar-link' %></li>
        <li class="col-md-2 navbar-button"><%= link_to 'DISCUSSION', questions_url, :class => 'navbar-link'  %></li>
        <% if session[:current_user] == nil || Plan.where(:to_user => :current_user).where(:read => false).count == 0 %>
          <li class="col-md-2 navbar-button"><%= link_to 'PLANS', plans_path, :class => 'navbar-link'  %></li>
        <% elsif Plan.where(:to_user => :current_user).where(:read => false).count > 0 %>
          <li class="col-md-2 navbar-button"><%= link_to 'PLANS(' + Plan.where(:to_user => :current_user).where(:read => false).count > 0 + ')', plans_path, :class => 'navbar-link'  %></li>
        <% end %>
        <li class="col-md-2 navbar-button"><%= link_to 'VIDEOS', videos_path, :class => 'navbar-link' %></li>
        <% if session[:current_user] == nil %>
          <li class="col-md-2 navbar-button"><%= link_to 'REGISTER', new_user_url, :class => 'navbar-link'  %></li>
          <li class="col-md-2 navbar-button"><%= link_to 'LOG IN', root_url + 'login', :class => 'navbar-link' %></li>
        <% else %>
          <% if User.find(session[:current_user]).is_admin %>
            <li class="col-md-2 navbar-button"><%= link_to 'CREATE ARTICLE', new_article_path, :class => 'navbar-link' %>
            <li class="col-md-2 navbar-button"><%= link_to 'REQUESTS', plan_requests_path, :class => 'navbar-link' %>
          <% end %>
          <% unread_messages = Message.where(:to_id => session[:current_user]).where(:read => false).count %>
          <% if unread_messages == 0 %>
            <li class="col-md-2 navbar-button"><%= link_to 'INBOX', messages_path, :class => 'navbar-link' %>
          <% elsif %>
            <li class="col-md-2 navbar-button"><%= link_to 'INBOX(' + unread_messages.to_s + ')', messages_path, :class => 'navbar-link' %>
          <% end %>
          <li class="col-md-2 navbar-button"><%= link_to 'LOG OUT', root_url + 'logout', :class => 'navbar-link' %></li>
        <% end %>
      </ul>
    </div> 
  </div>
  

  <div class="col-md-12 main-box">
    <% if flash[:success] != nil %>
    <div class="alert-success flash">
      <%= flash[:success] %>
    </div>
    <% end %>
    <% if flash[:danger] != nil %>
    <div class="alert-danger flash" >
      <%= flash[:danger] %>
    </div>
    <% end %>
    
    <div class="col-xs-0 col-sm-0 col-md-1 col-lg-1">
    </div>
    <a href="<%= plans_path %>" style="display:block;">
     <%= image_tag "advert", :class => "col-xs-12 col-sm-12 col-md-10 col-lg-10 banner_ad" %>
    </a>
    </br>
    <div class="col-xs-0 col-sm-0 col-md-1 col-lg-1">
    </div>
    
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <%= yield %>
    </div>
  </div>
</div>
</div>

<footer>
  <section class="footer-body">
    <small>
      Contact us at: truealfalife@gmail.com </br>
      <a href="https://www.facebook.com/pages/AlfaLife/1838549669721119">Facebook</a>
    </small>
  </section>
</footer>
</body>
</html>


<script>
  $(document).ready(new function(){
    $('.navbar-button').hover(
      
      function() {
      $(this).css('background', 'white');
      $(this).children().css('color', 'black');
    }, 
    
      function(){
        $(this).css('background', 'black');
        $(this).children().css('color', 'white');
    });
  });
  
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88795138-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/pages/home.html.erb
<div id="chat-wrapper">
    <div id="chat-box">
        Change this text
    </div>

    <div id="sender" onkeypress="sendMessage(event)">
        <input type="text" id="send-box" placeholder="Send message" /> 
    </div>
</div>

<script type='text/javascript'>
    function getMessage(message) {
        $('#chat-box').html($('#chat-box').html() + "</br>" + message);
    }

    function sendMessage(e) {
        if (e.which == 13 || e.keyCode == 13) {
            var message = document.getElementById('send-box').value;
            getMessage(message);
            document.getElementById('send-box').value == "";
        }
    }
</script>